///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace QLTQ
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MoChuongTrinh recording.
    /// </summary>
    [TestModule("cb1e53f4-b05b-4773-a06c-21e76810fa30", ModuleType.Recording, 1)]
    public partial class MoChuongTrinh : ITestModule
    {
        /// <summary>
        /// Holds an instance of the QLTQRepository repository.
        /// </summary>
        public static QLTQRepository repo = QLTQRepository.Instance;

        static MoChuongTrinh instance = new MoChuongTrinh();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MoChuongTrinh()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MoChuongTrinh Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Program Files (x86)\\Microsoft\\Setup\\Quanlytuyenquan.exe' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Program Files (x86)\\Microsoft\\Setup\\Quanlytuyenquan.exe", "", "C:\\Program Files (x86)\\Microsoft\\Setup", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmLogin1.TenDangNhap' at 12;10.", repo.FrmLogin1.TenDangNhapInfo, new RecordItemIndex(1));
            repo.FrmLogin1.TenDangNhap.Click("12;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'bodoi{Tab}' with focus on 'FrmLogin1.TenDangNhap'.", repo.FrmLogin1.TenDangNhapInfo, new RecordItemIndex(2));
            repo.FrmLogin1.TenDangNhap.PressKeys("bodoi{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '123456' with focus on 'FrmLogin1.MatKhau'.", repo.FrmLogin1.MatKhauInfo, new RecordItemIndex(3));
            repo.FrmLogin1.MatKhau.PressKeys("123456");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmLogin1.ĐăngNhập' at 43;6.", repo.FrmLogin1.ĐăngNhậpInfo, new RecordItemIndex(4));
            repo.FrmLogin1.ĐăngNhập.Click("43;6");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
