///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace QLTQ
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the QLTQRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    [RepositoryFolder("42b9c0b9-78af-49f7-b3f1-82e36bc68e43")]
    public partial class QLTQRepository : RepoGenBaseFolder
    {
        static QLTQRepository instance = new QLTQRepository();
        QLTQRepositoryFolders.FrmLoginAppFolder _frmlogin;
        QLTQRepositoryFolders.FrmmainAppFolder _frmmain;
        QLTQRepositoryFolders.ThongBaoAppFolder _thongbao;

        /// <summary>
        /// Gets the singleton class instance representing the QLTQRepository element repository.
        /// </summary>
        [RepositoryFolder("42b9c0b9-78af-49f7-b3f1-82e36bc68e43")]
        public static QLTQRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public QLTQRepository() 
            : base("QLTQRepository", "/", null, 0, false, "42b9c0b9-78af-49f7-b3f1-82e36bc68e43", ".\\RepositoryImages\\QLTQRepository42b9c0b9.rximgres")
        {
            _frmlogin = new QLTQRepositoryFolders.FrmLoginAppFolder(this);
            _frmmain = new QLTQRepositoryFolders.FrmmainAppFolder(this);
            _thongbao = new QLTQRepositoryFolders.ThongBaoAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("42b9c0b9-78af-49f7-b3f1-82e36bc68e43")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The FrmLogin folder.
        /// </summary>
        [RepositoryFolder("b9dbb0db-b244-41ec-9775-69003adf8f38")]
        public virtual QLTQRepositoryFolders.FrmLoginAppFolder FrmLogin
        {
            get { return _frmlogin; }
        }

        /// <summary>
        /// The Frmmain folder.
        /// </summary>
        [RepositoryFolder("80800de4-78f2-45e1-a8f0-f16ce07f3c6f")]
        public virtual QLTQRepositoryFolders.FrmmainAppFolder Frmmain
        {
            get { return _frmmain; }
        }

        /// <summary>
        /// The ThongBao folder.
        /// </summary>
        [RepositoryFolder("1224d4df-9a2f-418d-9eb1-6275708ae7a7")]
        public virtual QLTQRepositoryFolders.ThongBaoAppFolder ThongBao
        {
            get { return _thongbao; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
    public partial class QLTQRepositoryFolders
    {
        /// <summary>
        /// The FrmLoginAppFolder folder.
        /// </summary>
        [RepositoryFolder("b9dbb0db-b244-41ec-9775-69003adf8f38")]
        public partial class FrmLoginAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _đăngnhậpInfo;

            /// <summary>
            /// Creates a new FrmLogin  folder.
            /// </summary>
            public FrmLoginAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FrmLogin", "/form[@title='FrmLogin' and @processname='Quanlytuyenquan' and @controltypename='FrmLogin' and @instance='1']", parentFolder, 30000, null, true, "b9dbb0db-b244-41ec-9775-69003adf8f38", "")
            {
                _đăngnhậpInfo = new RepoItemInfo(this, "ĐăngNhập", ".//element[@controlname='btdangnhap']/button[@accessiblename='Đăng nhập']", 30000, null, "3f3cb6ff-e82c-4b5a-9f6d-d66e42bc5e77");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b9dbb0db-b244-41ec-9775-69003adf8f38")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b9dbb0db-b244-41ec-9775-69003adf8f38")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ĐăngNhập item.
            /// </summary>
            [RepositoryItem("3f3cb6ff-e82c-4b5a-9f6d-d66e42bc5e77")]
            public virtual Ranorex.Button ĐăngNhập
            {
                get
                {
                    return _đăngnhậpInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ĐăngNhập item info.
            /// </summary>
            [RepositoryItemInfo("3f3cb6ff-e82c-4b5a-9f6d-d66e42bc5e77")]
            public virtual RepoItemInfo ĐăngNhậpInfo
            {
                get
                {
                    return _đăngnhậpInfo;
                }
            }
        }

        /// <summary>
        /// The FrmmainAppFolder folder.
        /// </summary>
        [RepositoryFolder("80800de4-78f2-45e1-a8f0-f16ce07f3c6f")]
        public partial class FrmmainAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cậpnhậtdanhmụcInfo;
            RepoItemInfo _buttondivaligneqcenterwidtheq65xaphưInfo;
            RepoItemInfo _maxaInfo;
            RepoItemInfo _themInfo;

            /// <summary>
            /// Creates a new Frmmain  folder.
            /// </summary>
            public FrmmainAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Frmmain", "/form[@controlname='frmmain']", parentFolder, 30000, null, true, "80800de4-78f2-45e1-a8f0-f16ce07f3c6f", "")
            {
                _cậpnhậtdanhmụcInfo = new RepoItemInfo(this, "CậpNhậtDanhMục", "container[@controlname='ribbonControl1']/container[@controlname='ഭ']//button[@accessiblename='Cập nhật danh mục']", 30000, null, "d136a0bc-53c8-4aa1-9f67-133146a4a929");
                _buttondivaligneqcenterwidtheq65xaphưInfo = new RepoItemInfo(this, "ButtonDivAlignEqcenterWidthEq65XaPhư", "container[@controlname='ribbonControl1']/?/?/container[@controlname='ribbonBar2']/element/button[1]", 30000, null, "81e84ef9-7049-4b91-9a00-91a9e1de04a0");
                _maxaInfo = new RepoItemInfo(this, "MaXa", "container[@controlname='pnChua']//container[@controlname='pntren']/container[@controlname='groupPanel5']/text[@controlname='txt_maxaphuong']/text[@accessiblerole='Text']", 30000, null, "6b6c8066-7d48-43c3-9f65-fb2bc7a739dc");
                _themInfo = new RepoItemInfo(this, "Them", "container[@controlname='pnChua']//container[@controlname='pntren']/container[@controlname='groupPanel6']/?/?/button[@accessiblename='Thêm']", 30000, null, "e51dca11-6e5b-4992-ba53-0e59e582df6d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("80800de4-78f2-45e1-a8f0-f16ce07f3c6f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("80800de4-78f2-45e1-a8f0-f16ce07f3c6f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CậpNhậtDanhMục item.
            /// </summary>
            [RepositoryItem("d136a0bc-53c8-4aa1-9f67-133146a4a929")]
            public virtual Ranorex.Button CậpNhậtDanhMục
            {
                get
                {
                    return _cậpnhậtdanhmụcInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CậpNhậtDanhMục item info.
            /// </summary>
            [RepositoryItemInfo("d136a0bc-53c8-4aa1-9f67-133146a4a929")]
            public virtual RepoItemInfo CậpNhậtDanhMụcInfo
            {
                get
                {
                    return _cậpnhậtdanhmụcInfo;
                }
            }

            /// <summary>
            /// The ButtonDivAlignEqcenterWidthEq65XaPhư item.
            /// </summary>
            [RepositoryItem("81e84ef9-7049-4b91-9a00-91a9e1de04a0")]
            public virtual Ranorex.Button ButtonDivAlignEqcenterWidthEq65XaPhư
            {
                get
                {
                    return _buttondivaligneqcenterwidtheq65xaphưInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonDivAlignEqcenterWidthEq65XaPhư item info.
            /// </summary>
            [RepositoryItemInfo("81e84ef9-7049-4b91-9a00-91a9e1de04a0")]
            public virtual RepoItemInfo ButtonDivAlignEqcenterWidthEq65XaPhưInfo
            {
                get
                {
                    return _buttondivaligneqcenterwidtheq65xaphưInfo;
                }
            }

            /// <summary>
            /// The MaXa item.
            /// </summary>
            [RepositoryItem("6b6c8066-7d48-43c3-9f65-fb2bc7a739dc")]
            public virtual Ranorex.Text MaXa
            {
                get
                {
                    return _maxaInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The MaXa item info.
            /// </summary>
            [RepositoryItemInfo("6b6c8066-7d48-43c3-9f65-fb2bc7a739dc")]
            public virtual RepoItemInfo MaXaInfo
            {
                get
                {
                    return _maxaInfo;
                }
            }

            /// <summary>
            /// The Them item.
            /// </summary>
            [RepositoryItem("e51dca11-6e5b-4992-ba53-0e59e582df6d")]
            public virtual Ranorex.Button Them
            {
                get
                {
                    return _themInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Them item info.
            /// </summary>
            [RepositoryItemInfo("e51dca11-6e5b-4992-ba53-0e59e582df6d")]
            public virtual RepoItemInfo ThemInfo
            {
                get
                {
                    return _themInfo;
                }
            }
        }

        /// <summary>
        /// The ThongBaoAppFolder folder.
        /// </summary>
        [RepositoryFolder("1224d4df-9a2f-418d-9eb1-6275708ae7a7")]
        public partial class ThongBaoAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _megInfo;
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new ThongBao  folder.
            /// </summary>
            public ThongBaoAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ThongBao", "/form[@title='Thông báo']", parentFolder, 30000, null, true, "1224d4df-9a2f-418d-9eb1-6275708ae7a7", "")
            {
                _megInfo = new RepoItemInfo(this, "Meg", "text[@controlid='65535']", 30000, null, "439702f7-d2bf-4269-a05d-b7b035ab44d5");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@text='OK']", 30000, null, "9a5d06ef-5c5e-4eee-b5b0-bb28860a0b58");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1224d4df-9a2f-418d-9eb1-6275708ae7a7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1224d4df-9a2f-418d-9eb1-6275708ae7a7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Meg item.
            /// </summary>
            [RepositoryItem("439702f7-d2bf-4269-a05d-b7b035ab44d5")]
            public virtual Ranorex.Text Meg
            {
                get
                {
                    return _megInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Meg item info.
            /// </summary>
            [RepositoryItemInfo("439702f7-d2bf-4269-a05d-b7b035ab44d5")]
            public virtual RepoItemInfo MegInfo
            {
                get
                {
                    return _megInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("9a5d06ef-5c5e-4eee-b5b0-bb28860a0b58")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("9a5d06ef-5c5e-4eee-b5b0-bb28860a0b58")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}