///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace QLTQ
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ThemXaPhuong recording.
    /// </summary>
    [TestModule("df511d73-e74e-4175-a901-78727e74c841", ModuleType.Recording, 1)]
    public partial class ThemXaPhuong : ITestModule
    {
        /// <summary>
        /// Holds an instance of the QLTQRepository repository.
        /// </summary>
        public static QLTQRepository repo = QLTQRepository.Instance;

        static ThemXaPhuong instance = new ThemXaPhuong();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ThemXaPhuong()
        {
            MaXa = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ThemXaPhuong Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable MaXa.
        /// </summary>
        [TestVariable("bb277ca1-b862-4c05-9e1d-ce97cd3a72bf")]
        public string MaXa
        {
            get { return repo.MaXa; }
            set { repo.MaXa = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            // Them Xa Phuong
            Report.Log(ReportLevel.Info, "Section", "Them Xa Phuong", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Frmmain.CậpNhậtDanhMục' at 39;7.", repo.Frmmain.CậpNhậtDanhMụcInfo, new RecordItemIndex(1));
            repo.Frmmain.CậpNhậtDanhMục.Click("39;7");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Frmmain.XaPhuong' at 52;36.", repo.Frmmain.XaPhuongInfo, new RecordItemIndex(2));
            repo.Frmmain.XaPhuong.Click("52;36");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Frmmain.MaXa' at 7;5.", repo.Frmmain.MaXaInfo, new RecordItemIndex(3));
            repo.Frmmain.MaXa.Click("7;5");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'HA{Tab}' with focus on 'Frmmain.MaXa'.", repo.Frmmain.MaXaInfo, new RecordItemIndex(4));
            repo.Frmmain.MaXa.PressKeys("HA{Tab}");
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'Frmmain.MaXa' and assigning its value to variable 'MaXa'.", repo.Frmmain.MaXaInfo, new RecordItemIndex(5));
            MaXa = repo.Frmmain.MaXa.Element.GetAttributeValueText("Text");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'HoiAn'.", new RecordItemIndex(6));
            Keyboard.Press("HoiAn");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Frmmain.Them' at 86;8.", repo.Frmmain.ThemInfo, new RecordItemIndex(7));
            repo.Frmmain.Them.Click("86;8");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Bạn đã thêm thông tin thành công!') on item 'ThongBao.Meg'.", repo.ThongBao.MegInfo, new RecordItemIndex(8));
            Validate.Attribute(repo.ThongBao.MegInfo, "Text", "Bạn đã thêm thông tin thành công!");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongBao.ButtonOK' at 57;2.", repo.ThongBao.ButtonOKInfo, new RecordItemIndex(9));
            repo.ThongBao.ButtonOK.Click("57;2");
            
            ValidateXaPhuong(MaXa);
            
            // Xoa Xa Phuong
            Report.Log(ReportLevel.Info, "Section", "Xoa Xa Phuong", new RecordItemIndex(11));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Frmmain.PnChua.MaXaPhuong' at 68;12.", repo.Frmmain.PnChua.MaXaPhuongInfo, new RecordItemIndex(12));
            repo.Frmmain.PnChua.MaXaPhuong.Click("68;12");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Frmmain.PnChua.ButtonXoa' at 60;6.", repo.Frmmain.PnChua.ButtonXoaInfo, new RecordItemIndex(13));
            repo.Frmmain.PnChua.ButtonXoa.Click("60;6");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Bạn muốn xóa xã/phường này?') on item 'ThongBao.Meg'.", repo.ThongBao.MegInfo, new RecordItemIndex(14));
            Validate.Attribute(repo.ThongBao.MegInfo, "Text", "Bạn muốn xóa xã/phường này?");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongBao.ButtonOK' at 32;10.", repo.ThongBao.ButtonOKInfo, new RecordItemIndex(15));
            repo.ThongBao.ButtonOK.Click("32;10");
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Bạn đã xóa thông tin thành công!') on item 'ThongBao.Meg'.", repo.ThongBao.MegInfo, new RecordItemIndex(16));
            Validate.Attribute(repo.ThongBao.MegInfo, "Text", "Bạn đã xóa thông tin thành công!");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ThongBao.ButtonOK' at 39;15.", repo.ThongBao.ButtonOKInfo, new RecordItemIndex(17));
            repo.ThongBao.ButtonOK.Click("39;15");
            
            XoaXaPhuong(MaXa);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
